### ISSUE TITLE
Inconsistent String Formatting Syntax

### ISSUE THREAD

**Issue by brunomichetti** [rootstrap/django-drip-campaigns#41]
We need to review the code and apply changes to maintain a consistent string formatting syntax.
We need to be careful to use a formatting syntax that is compatible with python 3.5 and further.

**Comment by markrofail** [comment]
can I work on this? Would you like `f-strings`, `str.format()` or ` %-formatting`.

**Comment by kaozdl** [comment]
@markrofail 
Sure feel free to do it
we prefer f-strings but if it's too long use str.format
